/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/models": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Models */
        get: operations["models_models_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/preferences": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Preferences */
        get: operations["get_preferences_preferences_get"];
        put?: never;
        post?: never;
        /** Delete Preferences */
        delete: operations["delete_preferences_preferences_delete"];
        options?: never;
        head?: never;
        /** Patch Preferences */
        patch: operations["patch_preferences_preferences_patch"];
        trace?: never;
    };
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["health_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/articles": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Articles */
        get: operations["articles_articles_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/articles/{article_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Article */
        get: operations["article_articles__article_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/demo/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Demo Login */
        post: operations["demo_login_demo_login_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/sessions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Sessions */
        get: operations["list_sessions_sessions_get"];
        put?: never;
        /** New Session */
        post: operations["new_session_sessions_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/sessions/{session_id}/runs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Runs */
        get: operations["list_runs_sessions__session_id__runs_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/sessions/{session_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Session */
        get: operations["get_session_sessions__session_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/sessions/{session_id}/request": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Travel Request */
        get: operations["get_travel_request_sessions__session_id__request_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Patch Travel Request */
        patch: operations["patch_travel_request_sessions__session_id__request_patch"];
        trace?: never;
    };
    "/sessions/{session_id}/messages": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Message */
        post: operations["message_sessions__session_id__messages_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/runs/{run_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Run */
        get: operations["get_run_runs__run_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/runs/{run_id}/cancel": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Cancel Run */
        post: operations["cancel_run_runs__run_id__cancel_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/runs/{run_id}/events": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Events */
        get: operations["events_runs__run_id__events_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/plans/{plan_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Plan */
        get: operations["get_plan_plans__plan_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/plans/{plan_id}/calendar.ics": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Calendar */
        get: operations["get_calendar_plans__plan_id__calendar_ics_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/sessions/{session_id}/hotel-holds": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Hold Hotel */
        post: operations["hold_hotel_sessions__session_id__hotel_holds_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/sessions/{session_id}/bookings": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Session Bookings */
        get: operations["session_bookings_sessions__session_id__bookings_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/bookings/{booking_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Booking */
        get: operations["get_booking_bookings__booking_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/bookings/{booking_id}/confirm": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Confirm Booking */
        post: operations["confirm_booking_bookings__booking_id__confirm_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/bookings/{booking_id}/reconcile": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Reconcile Booking */
        post: operations["reconcile_booking_bookings__booking_id__reconcile_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/plan-drafts/{draft_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Draft */
        get: operations["get_draft_plan_drafts__draft_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/plan-drafts/{draft_id}/confirm": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Confirm Plan */
        post: operations["confirm_plan_plan_drafts__draft_id__confirm_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/plans/{plan_id}/locks": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Lock Items */
        patch: operations["lock_items_plans__plan_id__locks_patch"];
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** Article */
        Article: {
            /** Article Id */
            article_id: string;
            /**
             * City
             * @default 京都
             */
            city: string;
            /** Title */
            title: string;
            /** Text */
            text: string;
            /**
             * Category
             * @default guide
             */
            category: string;
            /**
             * Mentioned Places
             * @default []
             */
            mentioned_places: string[];
            source: components["schemas"]["Source"];
        };
        /** Booking */
        Booking: {
            /**
             * Booking Id
             * Format: uuid
             */
            booking_id: string;
            /**
             * Client Ref
             * Format: uuid
             */
            client_ref: string;
            /**
             * Session Id
             * Format: uuid
             */
            session_id: string;
            /**
             * Evidence Id
             * Format: uuid
             */
            evidence_id: string;
            offer: components["schemas"]["HotelOffer"];
            /** Total */
            total: string;
            /** Source Ref */
            source_ref: string;
            /** Content Version */
            content_version: string | null;
            /** @default quoted */
            status: components["schemas"]["BookingStatus"];
            /** Hold Id */
            hold_id: string | null;
            /** Expires At */
            expires_at: string | null;
            /** Order Id */
            order_id: string | null;
            error_code: components["schemas"]["ErrorCode"] | null;
            /**
             * History
             * @default []
             */
            history: components["schemas"]["BookingChange"][];
            /**
             * Data Mode
             * @default fixture
             * @constant
             */
            data_mode: "fixture";
        };
        /** BookingChange */
        BookingChange: {
            status: components["schemas"]["BookingStatus"];
            /**
             * At
             * Format: date-time
             */
            at: string;
            /** Reason */
            reason: string;
        };
        /** @enum {string} */
        BookingStatus: "quoted" | "held" | "confirmed" | "booked" | "failed" | "unknown" | "expired";
        /** BudgetRange */
        "BudgetRange-Input": {
            /** Lower */
            lower?: number | string | null;
            /** Upper */
            upper?: number | string | null;
        };
        /** BudgetRange */
        "BudgetRange-Output": {
            /** Lower */
            lower?: string | null;
            /** Upper */
            upper?: string | null;
        };
        /** BudgetRelation */
        BudgetRelation: {
            /**
             * Status
             * @enum {string}
             */
            status: "conflict" | "warning" | "unknown" | "within";
            /** Total Lower */
            total_lower?: string | null;
            /** Total Upper */
            total_upper?: string | null;
            /** Currency */
            currency?: string | null;
            /** Message */
            message: string;
        };
        /** @enum {string} */
        BusinessKind: "answer_only" | "draft_staged" | "stage_failed" | "confirmed";
        /**
         * BusinessResult
         * @description Small server facts; never derive a business commit from runtime text.
         */
        BusinessResult: {
            kind: components["schemas"]["BusinessKind"];
            /** Draft Id */
            draft_id?: string | null;
            /** Plan Id */
            plan_id?: string | null;
            /** Validation Status */
            validation_status?: ("complete" | "partial" | "conflict") | null;
            code?: components["schemas"]["ErrorCode"] | null;
            reason?: components["schemas"]["StageReason"] | null;
            /** Version */
            version?: number | null;
        };
        /** DemoIdentity */
        DemoIdentity: {
            /**
             * User Id
             * Format: uuid
             */
            user_id: string;
            /** Token */
            token: string;
            /**
             * Expires At
             * Format: date-time
             */
            expires_at: string;
        };
        /** DemoLogin */
        DemoLogin: {
            /**
             * Display Name
             * @default 旅行者
             */
            display_name: string;
        };
        /** @enum {string} */
        ErrorCode: "validation" | "blocked" | "unavailable" | "timeout" | "rate_limited" | "provider_error" | "conflict" | "cancelled";
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** HistoricalRun */
        HistoricalRun: {
            /**
             * Run Id
             * Format: uuid
             */
            run_id: string;
            /**
             * Session Id
             * Format: uuid
             */
            session_id: string;
            /** Status */
            status: string;
            /** Mode */
            mode: string;
            /** Answer */
            answer: string;
            /** Error Code */
            error_code: string | null;
            /** Last Sequence */
            last_sequence: number;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Presentations
             * @default []
             */
            presentations: {
                [key: string]: unknown;
            }[];
            business_result?: components["schemas"]["BusinessResult"] | null;
            /**
             * Prompt
             * @default
             */
            prompt: string;
            /** Draft Id */
            draft_id?: string | null;
        };
        /** HoldHotelInput */
        HoldHotelInput: {
            /**
             * Offer Id
             * Format: uuid
             */
            offer_id: string;
            /** Expected Revision */
            expected_revision: number;
        };
        /** HotelCard */
        HotelCard: {
            /** Address */
            address?: string | null;
            /** Latitude */
            latitude?: number | null;
            /** Longitude */
            longitude?: number | null;
            /** Review Count */
            review_count?: number | null;
            /** Hotel Info Url */
            hotel_info_url?: string | null;
            /** Plan List Url */
            plan_list_url?: string | null;
            /** Reservation Url */
            reservation_url?: string | null;
            /** Price Basis */
            price_basis?: string | null;
            /**
             * Offer Id
             * Format: uuid
             */
            offer_id: string;
            /** Rate Id */
            rate_id: string;
            /** Hotel Id */
            hotel_id: string;
            /** Hotel Name */
            hotel_name: string;
            /** Room Type */
            room_type: string;
            /** Currency */
            currency: string;
            /** Base Amount */
            base_amount: string;
            /** Tax Amount */
            tax_amount: string | null;
            /** Fee Amount */
            fee_amount: string | null;
            /** Breakfast */
            breakfast: boolean | null;
            /** Refundable */
            refundable: boolean | null;
            /** Image Url */
            image_url?: string | null;
            /** Review Average */
            review_average?: number | null;
            /** Booking Url */
            booking_url?: string | null;
            /**
             * Data Mode
             * @enum {string}
             */
            data_mode: "fixture" | "live";
            /** Included Total */
            included_total?: string | null;
            /** Total Reason */
            total_reason?: string | null;
            /**
             * Quoted At
             * Format: date-time
             */
            quoted_at: string;
            /**
             * Expires At
             * Format: date-time
             */
            expires_at: string;
            /**
             * Room Tags
             * @default []
             */
            room_tags: string[];
            /**
             * Qualification Unknown
             * @default false
             */
            qualification_unknown: boolean;
            /**
             * Room Preference Mismatch
             * @default false
             */
            room_preference_mismatch: boolean;
            /** Stay */
            stay: {
                [key: string]: unknown;
            };
            /** Request Revision */
            request_revision: number;
            /** Total */
            total: string | null;
            /** Lodging Exceeds Trip Budget */
            lodging_exceeds_trip_budget: boolean | null;
            /** Lodging Exceeds Lodging Budget */
            lodging_exceeds_lodging_budget?: boolean | null;
            /**
             * Evidence Id
             * Format: uuid
             */
            evidence_id: string;
            /** Source Ref */
            source_ref: string | null;
            /** Content Version */
            content_version: string | null;
        };
        /** HotelOffer */
        HotelOffer: {
            /**
             * Offer Id
             * Format: uuid
             */
            offer_id: string;
            /** Rate Id */
            rate_id: string;
            /** Hotel Id */
            hotel_id: string;
            /** Hotel Name */
            hotel_name: string;
            /** Room Type */
            room_type: string;
            /** Currency */
            currency: string;
            /** Base Amount */
            base_amount: string;
            /** Tax Amount */
            tax_amount: string | null;
            /** Fee Amount */
            fee_amount: string | null;
            /** Breakfast */
            breakfast: boolean | null;
            /** Refundable */
            refundable: boolean | null;
            /** Image Url */
            image_url: string | null;
            /** Review Average */
            review_average: number | null;
            /** Booking Url */
            booking_url: string | null;
            /**
             * Data Mode
             * @default fixture
             * @enum {string}
             */
            data_mode: "fixture" | "live";
            /** Included Total */
            included_total: string | null;
            /** Total Reason */
            total_reason: string | null;
            /**
             * Quoted At
             * Format: date-time
             */
            quoted_at: string;
            /**
             * Expires At
             * Format: date-time
             */
            expires_at: string;
            request: components["schemas"]["LegacyRequestSnapshot"];
        };
        /**
         * HotelStay
         * @description 兼容读取分段住宿；写入与业务约束在后续任务启用。
         */
        HotelStay: {
            /**
             * Check In
             * Format: date
             */
            check_in: string;
            /**
             * Check Out
             * Format: date
             */
            check_out: string;
            /**
             * Hotel Evidence Id
             * Format: uuid
             */
            hotel_evidence_id: string;
        };
        /** ItemDiff */
        ItemDiff: {
            /**
             * Item Id
             * Format: uuid
             */
            item_id: string;
            /**
             * Op
             * @enum {string}
             */
            op: "add" | "update" | "remove";
            before?: components["schemas"]["PlanItem"] | null;
            after?: components["schemas"]["PlanItem"] | null;
        };
        /**
         * LegacyRequestSnapshot
         * @description 明确的旧快照输出类型，保留schema类型但不序列化新增预算。
         */
        LegacyRequestSnapshot: {
            /** City */
            city?: string | null;
            /** Start Date */
            start_date?: string | null;
            /** End Date */
            end_date?: string | null;
            /**
             * Timezone
             * @default Asia/Tokyo
             * @constant
             */
            timezone: "Asia/Tokyo";
            /** Adults */
            adults?: number | null;
            /** Child Ages */
            child_ages?: number[] | null;
            /** Rooms */
            rooms?: number | null;
            /** Budget */
            budget?: string | null;
            /**
             * Currency
             * @default JPY
             * @constant
             */
            currency: "JPY";
            /** Transport */
            transport?: ("walk" | "transit" | "taxi") | null;
            /**
             * Departure Time
             * @description 每天开始游玩的当地时间，仅在用户明确每日出发时设置。不是首日抵达时间、末日返程或航班/车次时间；这些带日期和角色写入hard_constraints。未说明每日出发时不要填；用户明确纠正旧误填时清除此字段。
             */
            departure_time?: string | null;
            /**
             * Interests
             * @default []
             */
            interests: string[];
            /**
             * Hard Constraints
             * @default []
             */
            hard_constraints: string[];
            /**
             * Soft Constraints
             * @default []
             */
            soft_constraints: string[];
            /**
             * Revision
             * @default 0
             */
            revision: number;
        };
        /** LockInput */
        LockInput: {
            /** Expected Version */
            expected_version: number;
            /** Locked Item Ids */
            locked_item_ids: string[];
        };
        /** LodgingBudget */
        "LodgingBudget-Input": {
            amount: components["schemas"]["BudgetRange-Input"];
            /**
             * Basis
             * @enum {string}
             */
            basis: "per_room_night" | "total";
            /** Currency */
            currency: string;
        };
        /** LodgingBudget */
        "LodgingBudget-Output": {
            amount: components["schemas"]["BudgetRange-Output"];
            /**
             * Basis
             * @enum {string}
             */
            basis: "per_room_night" | "total";
            /** Currency */
            currency: string;
        };
        /** MessageInput */
        MessageInput: {
            /**
             * Client Message Id
             * Format: uuid
             */
            client_message_id: string;
            /** Text */
            text: string;
            /**
             * Mode
             * @default offline
             * @enum {string}
             */
            mode: "offline" | "deepseek" | "claude";
        };
        /** ModelOption */
        ModelOption: {
            /**
             * Id
             * @enum {string}
             */
            id: "offline" | "deepseek" | "claude";
            /** Label */
            label: string;
            /** Available */
            available: boolean;
            /** Reason */
            reason?: string | null;
        };
        /** PlanCard */
        PlanCard: {
            /**
             * Place Evidence Id
             * Format: uuid
             * @description 仅用search_places/get_place_facts返回的kind=place的evidence_id；不是place_id，也不能用酒店报价或route证据ID
             */
            place_evidence_id: string;
            /**
             * Start
             * Format: date-time
             * @description 含时区的ISO时间；日本时间使用+09:00
             */
            start: string;
            /**
             * End
             * Format: date-time
             * @description 含时区的ISO时间；日本时间使用+09:00
             */
            end: string;
            /**
             * Route Evidence Id
             * @description 本项的入站路段：仅用estimate_routes返回的kind=route的evidence_id，起点须为同一天前一景点、终点须为本景点；每天首项必须省略。不要把出站路段挂到前一项，不用route_id代替evidence_id
             */
            route_evidence_id: string | null;
            /**
             * Note
             * @description 一句话概述，模型撰写，非来源核实
             */
            note: string | null;
            /**
             * Item Id
             * Format: uuid
             */
            item_id: string;
            /**
             * Locked
             * @default false
             */
            locked: boolean;
            /** Name */
            name: string;
            /** Source Ref */
            source_ref: string | null;
            /**
             * Data Mode
             * @enum {string}
             */
            data_mode: "fixture" | "snapshot" | "live";
        };
        /** PlanContent */
        PlanContent: {
            /** Items */
            items: components["schemas"]["PlanItem"][];
            /** Hotel Evidence Id */
            hotel_evidence_id?: string | null;
            /**
             * Hotel Stays
             * @default []
             */
            hotel_stays: components["schemas"]["HotelStay"][];
        };
        /** PlanItem */
        PlanItem: {
            /**
             * Place Evidence Id
             * Format: uuid
             * @description 仅用search_places/get_place_facts返回的kind=place的evidence_id；不是place_id，也不能用酒店报价或route证据ID
             */
            place_evidence_id: string;
            /**
             * Start
             * Format: date-time
             * @description 含时区的ISO时间；日本时间使用+09:00
             */
            start: string;
            /**
             * End
             * Format: date-time
             * @description 含时区的ISO时间；日本时间使用+09:00
             */
            end: string;
            /**
             * Route Evidence Id
             * @description 本项的入站路段：仅用estimate_routes返回的kind=route的evidence_id，起点须为同一天前一景点、终点须为本景点；每天首项必须省略。不要把出站路段挂到前一项，不用route_id代替evidence_id
             */
            route_evidence_id?: string | null;
            /**
             * Note
             * @description 一句话概述，模型撰写，非来源核实
             */
            note?: string | null;
            /**
             * Item Id
             * Format: uuid
             */
            item_id?: string;
            /**
             * Locked
             * @default false
             */
            locked: boolean;
        };
        /** PlanView */
        PlanView: {
            /**
             * Plan Id
             * Format: uuid
             */
            plan_id: string;
            /** Request Revision */
            request_revision: number;
            /** Cards */
            cards: components["schemas"]["PlanCard"][];
            hotel: components["schemas"]["HotelCard"] | null;
            /** Hotel Evidence Id */
            hotel_evidence_id: string | null;
            /**
             * Hotel Stays
             * @default []
             */
            hotel_stays: components["schemas"]["HotelStay"][];
            /** Needs Refresh */
            needs_refresh: string[];
            validation: components["schemas"]["ValidationFeedback"];
            /** Guidance */
            guidance: string;
            /** Version */
            version: number | null;
            /** Saved At */
            saved_at: string | null;
            /**
             * Historical
             * @default false
             */
            historical: boolean;
            /** Draft Id */
            draft_id: string | null;
            /** Base Version */
            base_version: number | null;
            /**
             * Changes
             * @default []
             */
            changes: components["schemas"]["ItemDiff"][];
            /**
             * Hotel Changed
             * @default false
             */
            hotel_changed: boolean;
            /** Expires At */
            expires_at: string | null;
            /** Status */
            status: ("staged" | "confirmed") | null;
            /**
             * Expired
             * @default false
             */
            expired: boolean;
            /**
             * Conditions Changed
             * @default false
             */
            conditions_changed: boolean;
            /**
             * Version Changed
             * @default false
             */
            version_changed: boolean;
        };
        /** PreferencePatch */
        PreferencePatch: {
            /** Expected Revision */
            expected_revision: number;
            set: components["schemas"]["PreferenceValues"];
        };
        /** PreferenceValues */
        PreferenceValues: {
            /**
             * Interests
             * @default []
             */
            interests: string[];
            /**
             * Soft Constraints
             * @default []
             */
            soft_constraints: string[];
            /** Transport */
            transport?: ("walk" | "transit" | "taxi") | null;
        };
        /** PreferenceVersion */
        PreferenceVersion: {
            /** Expected Revision */
            expected_revision: number;
        };
        /** Preferences */
        Preferences: {
            /**
             * Interests
             * @default []
             */
            interests: string[];
            /**
             * Soft Constraints
             * @default []
             */
            soft_constraints: string[];
            /** Transport */
            transport?: ("walk" | "transit" | "taxi") | null;
            /**
             * Revision
             * @default 0
             */
            revision: number;
        };
        /** RequestPatch */
        RequestPatch: {
            /** Expected Revision */
            expected_revision: number;
            set?: components["schemas"]["TravelConditions"];
            /**
             * Clear
             * @default []
             */
            clear: string[];
        };
        /** RequestUpdateView */
        RequestUpdateView: {
            request: components["schemas"]["RequestView"];
            /** Changed Fields */
            changed_fields: string[];
            /**
             * Skipped Fields
             * @default []
             */
            skipped_fields: string[];
        };
        /** RequestView */
        RequestView: {
            /** City */
            city?: string | null;
            /**
             * Hotel Search Location
             * @description 用户明确指定的住宿查询城市或地点，保留旅行city不变；省级范围须进一步细化
             */
            hotel_search_location?: string | null;
            /** Start Date */
            start_date?: string | null;
            /** End Date */
            end_date?: string | null;
            /**
             * Timezone
             * @default Asia/Tokyo
             * @constant
             */
            timezone: "Asia/Tokyo";
            /** Adults */
            adults?: number | null;
            /** Child Ages */
            child_ages?: number[] | null;
            /** Rooms */
            rooms?: number | null;
            /** Budget */
            budget?: string | null;
            /**
             * Currency
             * @default JPY
             * @constant
             */
            currency: "JPY";
            lodging_budget?: components["schemas"]["LodgingBudget-Output"] | null;
            /** Transport */
            transport?: ("walk" | "transit" | "taxi") | null;
            /**
             * Departure Time
             * @description 每天开始游玩的当地时间，仅在用户明确每日出发时设置。不是首日抵达时间、末日返程或航班/车次时间；这些带日期和角色写入hard_constraints。未说明每日出发时不要填；用户明确纠正旧误填时清除此字段。
             */
            departure_time?: string | null;
            /**
             * Interests
             * @default []
             */
            interests: string[];
            /**
             * Hard Constraints
             * @default []
             */
            hard_constraints: string[];
            /**
             * Soft Constraints
             * @default []
             */
            soft_constraints: string[];
            /**
             * Revision
             * @default 0
             */
            revision: number;
            /** Segments */
            segments?: components["schemas"]["TripSegment"][] | null;
            /**
             * Lodging Budget Unlimited
             * @default false
             */
            lodging_budget_unlimited: boolean;
            budget_relation: components["schemas"]["BudgetRelation"];
            /** Field Sources */
            field_sources?: {
                [key: string]: "conversation" | "user_form" | "none";
            };
        };
        /** RunPage */
        RunPage: {
            /** Items */
            items: components["schemas"]["HistoricalRun"][];
            /** Next Before */
            next_before: string | null;
        };
        /** RunView */
        RunView: {
            /**
             * Run Id
             * Format: uuid
             */
            run_id: string;
            /**
             * Session Id
             * Format: uuid
             */
            session_id: string;
            /** Status */
            status: string;
            /** Mode */
            mode: string;
            /** Answer */
            answer: string;
            /** Error Code */
            error_code: string | null;
            /** Last Sequence */
            last_sequence: number;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Presentations
             * @default []
             */
            presentations: {
                [key: string]: unknown;
            }[];
            business_result?: components["schemas"]["BusinessResult"] | null;
        };
        /** SavedPlan */
        SavedPlan: {
            /**
             * Plan Id
             * Format: uuid
             */
            plan_id: string;
            /** Version */
            version: number;
            /** Request Revision */
            request_revision: number;
            content: components["schemas"]["PlanContent"];
            validation: components["schemas"]["ValidationReport"];
            /**
             * Saved At
             * Format: date-time
             */
            saved_at: string;
        };
        /** SessionPage */
        SessionPage: {
            /** Items */
            items: components["schemas"]["SessionSummary"][];
            /** Next Cursor */
            next_cursor: string | null;
        };
        /** SessionSummary */
        SessionSummary: {
            /**
             * Session Id
             * Format: uuid
             */
            session_id: string;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** City */
            city: string | null;
            /** Start Date */
            start_date: string | null;
            /** End Date */
            end_date: string | null;
            /** Plan Id */
            plan_id: string | null;
            /** Current Version */
            current_version: number | null;
            /**
             * Last Activity At
             * Format: date-time
             */
            last_activity_at: string;
        };
        /** SessionView */
        SessionView: {
            /**
             * Session Id
             * Format: uuid
             */
            session_id: string;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
        };
        /** Source */
        Source: {
            /**
             * Provider
             * @enum {string}
             */
            provider: "osm" | "wikivoyage" | "google_places";
            /** Source Ref */
            source_ref: string;
            /** Content Version */
            content_version: string;
            /**
             * Retrieved At
             * Format: date-time
             */
            retrieved_at: string;
            /** License */
            license: string;
            /** License Url */
            license_url: string;
            /** Attribution */
            attribution: string;
            /**
             * Data Mode
             * @default snapshot
             * @enum {string}
             */
            data_mode: "snapshot" | "live";
        };
        /** @enum {string} */
        StageReason: "plan_exists" | "patch_invalid" | "repair_limit" | "other";
        /**
         * StoredHotelDetails
         * @description 随证据保存的展示细节；比卡片多出本次搜索的整体信息，由present提到展示顶层，不进卡片。
         */
        StoredHotelDetails: {
            /** Address */
            address?: string | null;
            /** Latitude */
            latitude?: number | null;
            /** Longitude */
            longitude?: number | null;
            /** Review Count */
            review_count?: number | null;
            /** Hotel Info Url */
            hotel_info_url?: string | null;
            /** Plan List Url */
            plan_list_url?: string | null;
            /** Reservation Url */
            reservation_url?: string | null;
            /** Price Basis */
            price_basis?: string | null;
            /** Search Total Found */
            search_total_found?: number | null;
            /** More Url */
            more_url?: string | null;
            /** More Url Scope */
            more_url_scope?: ("search" | "destination") | null;
        };
        /** TravelConditions */
        TravelConditions: {
            /** City */
            city?: string | null;
            /**
             * Hotel Search Location
             * @description 用户明确指定的住宿查询城市或地点，保留旅行city不变；省级范围须进一步细化
             */
            hotel_search_location?: string | null;
            /** Start Date */
            start_date?: string | null;
            /** End Date */
            end_date?: string | null;
            /**
             * Timezone
             * @default Asia/Tokyo
             * @constant
             */
            timezone: "Asia/Tokyo";
            /** Adults */
            adults?: number | null;
            /** Child Ages */
            child_ages?: number[] | null;
            /** Rooms */
            rooms?: number | null;
            /** Budget */
            budget?: number | string | null;
            /**
             * Currency
             * @default JPY
             * @constant
             */
            currency: "JPY";
            lodging_budget?: components["schemas"]["LodgingBudget-Input"] | null;
            /** Transport */
            transport?: ("walk" | "transit" | "taxi") | null;
            /**
             * Departure Time
             * @description 每天开始游玩的当地时间，仅在用户明确每日出发时设置。不是首日抵达时间、末日返程或航班/车次时间；这些带日期和角色写入hard_constraints。未说明每日出发时不要填；用户明确纠正旧误填时清除此字段。
             */
            departure_time?: string | null;
            /**
             * Interests
             * @default []
             */
            interests: string[];
            /**
             * Hard Constraints
             * @default []
             */
            hard_constraints: string[];
            /**
             * Soft Constraints
             * @default []
             */
            soft_constraints: string[];
        };
        /** TravelRequest */
        TravelRequest: {
            /** City */
            city?: string | null;
            /**
             * Hotel Search Location
             * @description 用户明确指定的住宿查询城市或地点，保留旅行city不变；省级范围须进一步细化
             */
            hotel_search_location?: string | null;
            /** Start Date */
            start_date?: string | null;
            /** End Date */
            end_date?: string | null;
            /**
             * Timezone
             * @default Asia/Tokyo
             * @constant
             */
            timezone: "Asia/Tokyo";
            /** Adults */
            adults?: number | null;
            /** Child Ages */
            child_ages?: number[] | null;
            /** Rooms */
            rooms?: number | null;
            /** Budget */
            budget?: string | null;
            /**
             * Currency
             * @default JPY
             * @constant
             */
            currency: "JPY";
            lodging_budget?: components["schemas"]["LodgingBudget-Output"] | null;
            /** Transport */
            transport?: ("walk" | "transit" | "taxi") | null;
            /**
             * Departure Time
             * @description 每天开始游玩的当地时间，仅在用户明确每日出发时设置。不是首日抵达时间、末日返程或航班/车次时间；这些带日期和角色写入hard_constraints。未说明每日出发时不要填；用户明确纠正旧误填时清除此字段。
             */
            departure_time?: string | null;
            /**
             * Interests
             * @default []
             */
            interests: string[];
            /**
             * Hard Constraints
             * @default []
             */
            hard_constraints: string[];
            /**
             * Soft Constraints
             * @default []
             */
            soft_constraints: string[];
            /**
             * Revision
             * @default 0
             */
            revision: number;
            /** Segments */
            segments?: components["schemas"]["TripSegment"][] | null;
            /**
             * Lodging Budget Unlimited
             * @default false
             */
            lodging_budget_unlimited: boolean;
        };
        /**
         * TripSegment
         * @description 读取持久化城市段；连续性与写入派生在T1.1启用。
         */
        TripSegment: {
            /** City */
            city: string;
            /**
             * Arrive
             * Format: date
             */
            arrive: string;
            /**
             * Depart
             * Format: date
             */
            depart: string;
            /** Hotel Search Location */
            hotel_search_location?: string | null;
        };
        /** ValidationCheck */
        ValidationCheck: {
            /** Subject */
            subject: string;
            /**
             * Status
             * @enum {string}
             */
            status: "verified" | "unknown" | "conflict";
            /** Code */
            code: string;
            /** Message */
            message: string;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
        /** ValidationFeedback */
        ValidationFeedback: {
            /**
             * Status
             * @enum {string}
             */
            status: "complete" | "partial" | "conflict";
            /** Checks */
            checks: components["schemas"]["ValidationCheck"][];
            /** Known Cost */
            known_cost: string;
            /** Estimated Cost */
            estimated_cost: string;
            /**
             * Scope
             * @default 按当前来源与报价校验；路线时长为估算，临时闭馆与未核实费用仍需出行前确认
             */
            scope: string;
            /** Check Counts */
            check_counts: {
                [key: string]: number;
            };
            /** Truncated */
            truncated: boolean;
        };
        /** ValidationReport */
        ValidationReport: {
            /**
             * Status
             * @enum {string}
             */
            status: "complete" | "partial" | "conflict";
            /** Checks */
            checks: components["schemas"]["ValidationCheck"][];
            /** Known Cost */
            known_cost: string;
            /** Estimated Cost */
            estimated_cost: string;
            /**
             * Scope
             * @default 按当前来源与报价校验；路线时长为估算，临时闭馆与未核实费用仍需出行前确认
             */
            scope: string;
        };
        /** BudgetRelation */
        UiBudgetRelation: {
            /**
             * Status
             * @enum {string}
             */
            status: "conflict" | "warning" | "unknown" | "within";
            /**
             * Total Lower
             * @default null
             */
            total_lower: string | null;
            /**
             * Total Upper
             * @default null
             */
            total_upper: string | null;
            /**
             * Currency
             * @default null
             */
            currency: string | null;
            /** Message */
            message: string;
        };
        /** Comparison */
        UiComparison: {
            /**
             * Room Preferences Question
             * @default null
             */
            room_preferences_question: string | null;
            /** @default null */
            budget_relation: components["schemas"]["UiBudgetRelation"] | null;
            /** Comparable */
            comparable: boolean;
            /** Reasons */
            reasons: string[];
            /** Lowest Offer Ids */
            lowest_offer_ids: string[];
            /** Scope */
            scope: string;
        };
        /** HotelCard */
        UiHotelCard: {
            /**
             * Address
             * @default null
             */
            address: string | null;
            /**
             * Latitude
             * @default null
             */
            latitude: number | null;
            /**
             * Longitude
             * @default null
             */
            longitude: number | null;
            /**
             * Review Count
             * @default null
             */
            review_count: number | null;
            /**
             * Hotel Info Url
             * @default null
             */
            hotel_info_url: string | null;
            /**
             * Plan List Url
             * @default null
             */
            plan_list_url: string | null;
            /**
             * Reservation Url
             * @default null
             */
            reservation_url: string | null;
            /**
             * Price Basis
             * @default null
             */
            price_basis: string | null;
            /**
             * Offer Id
             * Format: uuid
             */
            offer_id: string;
            /** Rate Id */
            rate_id: string;
            /** Hotel Id */
            hotel_id: string;
            /** Hotel Name */
            hotel_name: string;
            /** Room Type */
            room_type: string;
            /** Currency */
            currency: string;
            /** Base Amount */
            base_amount: string;
            /** Tax Amount */
            tax_amount: string | null;
            /** Fee Amount */
            fee_amount: string | null;
            /** Breakfast */
            breakfast: boolean | null;
            /** Refundable */
            refundable: boolean | null;
            /**
             * Image Url
             * @default null
             */
            image_url: string | null;
            /**
             * Review Average
             * @default null
             */
            review_average: number | null;
            /**
             * Booking Url
             * @default null
             */
            booking_url: string | null;
            /**
             * Data Mode
             * @enum {string}
             */
            data_mode: "fixture" | "live";
            /**
             * Included Total
             * @default null
             */
            included_total: string | null;
            /**
             * Total Reason
             * @default null
             */
            total_reason: string | null;
            /**
             * Quoted At
             * Format: date-time
             */
            quoted_at: string;
            /**
             * Expires At
             * Format: date-time
             */
            expires_at: string;
            /**
             * Room Tags
             * @default []
             */
            room_tags: string[];
            /**
             * Qualification Unknown
             * @default false
             */
            qualification_unknown: boolean;
            /**
             * Room Preference Mismatch
             * @default false
             */
            room_preference_mismatch: boolean;
            /** Stay */
            stay: {
                [key: string]: unknown;
            };
            /** Request Revision */
            request_revision: number;
            /** Total */
            total: string | null;
            /** Lodging Exceeds Trip Budget */
            lodging_exceeds_trip_budget: boolean | null;
            /**
             * Lodging Exceeds Lodging Budget
             * @default null
             */
            lodging_exceeds_lodging_budget: boolean | null;
            /**
             * Evidence Id
             * Format: uuid
             */
            evidence_id: string;
            /** Source Ref */
            source_ref: string | null;
            /** Content Version */
            content_version: string | null;
        };
        /** HotelPresentation */
        UiHotelPresentation: {
            /**
             * Component
             * @constant
             */
            component: "hotel_comparison";
            /** Cards */
            cards: components["schemas"]["UiHotelCard"][];
            comparison: components["schemas"]["UiComparison"];
            /**
             * Total Found
             * @default null
             */
            total_found: number | null;
            /**
             * More Url
             * @default null
             */
            more_url: string | null;
            /**
             * More Url Scope
             * @default null
             */
            more_url_scope: ("search" | "destination") | null;
        };
        /**
         * HotelStay
         * @description 兼容读取分段住宿；写入与业务约束在后续任务启用。
         */
        UiHotelStay: {
            /**
             * Check In
             * Format: date
             */
            check_in: string;
            /**
             * Check Out
             * Format: date
             */
            check_out: string;
            /**
             * Hotel Evidence Id
             * Format: uuid
             */
            hotel_evidence_id: string;
        };
        /** ItemDiff */
        UiItemDiff: {
            /**
             * Item Id
             * Format: uuid
             */
            item_id: string;
            /**
             * Op
             * @enum {string}
             */
            op: "add" | "update" | "remove";
            /** @default null */
            before: components["schemas"]["UiPlanItem"] | null;
            /** @default null */
            after: components["schemas"]["UiPlanItem"] | null;
        };
        /** PlanCard */
        UiPlanCard: {
            /**
             * Place Evidence Id
             * Format: uuid
             * @description 仅用search_places/get_place_facts返回的kind=place的evidence_id；不是place_id，也不能用酒店报价或route证据ID
             */
            place_evidence_id: string;
            /**
             * Start
             * Format: date-time
             * @description 含时区的ISO时间；日本时间使用+09:00
             */
            start: string;
            /**
             * End
             * Format: date-time
             * @description 含时区的ISO时间；日本时间使用+09:00
             */
            end: string;
            /**
             * Route Evidence Id
             * @description 本项的入站路段：仅用estimate_routes返回的kind=route的evidence_id，起点须为同一天前一景点、终点须为本景点；每天首项必须省略。不要把出站路段挂到前一项，不用route_id代替evidence_id
             * @default null
             */
            route_evidence_id: string | null;
            /**
             * Note
             * @description 一句话概述，模型撰写，非来源核实
             * @default null
             */
            note: string | null;
            /**
             * Item Id
             * Format: uuid
             */
            item_id: string;
            /**
             * Locked
             * @default false
             */
            locked: boolean;
            /** Name */
            name: string;
            /** Source Ref */
            source_ref: string | null;
            /**
             * Data Mode
             * @enum {string}
             */
            data_mode: "fixture" | "snapshot" | "live";
        };
        /** PlanItem */
        UiPlanItem: {
            /**
             * Place Evidence Id
             * Format: uuid
             * @description 仅用search_places/get_place_facts返回的kind=place的evidence_id；不是place_id，也不能用酒店报价或route证据ID
             */
            place_evidence_id: string;
            /**
             * Start
             * Format: date-time
             * @description 含时区的ISO时间；日本时间使用+09:00
             */
            start: string;
            /**
             * End
             * Format: date-time
             * @description 含时区的ISO时间；日本时间使用+09:00
             */
            end: string;
            /**
             * Route Evidence Id
             * @description 本项的入站路段：仅用estimate_routes返回的kind=route的evidence_id，起点须为同一天前一景点、终点须为本景点；每天首项必须省略。不要把出站路段挂到前一项，不用route_id代替evidence_id
             * @default null
             */
            route_evidence_id: string | null;
            /**
             * Note
             * @description 一句话概述，模型撰写，非来源核实
             * @default null
             */
            note: string | null;
            /**
             * Item Id
             * Format: uuid
             */
            item_id?: string;
            /**
             * Locked
             * @default false
             */
            locked: boolean;
        };
        /** PlanView */
        UiPlanView: {
            /**
             * Plan Id
             * Format: uuid
             */
            plan_id: string;
            /** Request Revision */
            request_revision: number;
            /** Cards */
            cards: components["schemas"]["UiPlanCard"][];
            hotel: components["schemas"]["UiHotelCard"] | null;
            /** Hotel Evidence Id */
            hotel_evidence_id: string | null;
            /**
             * Hotel Stays
             * @default []
             */
            hotel_stays: components["schemas"]["UiHotelStay"][];
            /** Needs Refresh */
            needs_refresh: string[];
            validation: components["schemas"]["UiValidationFeedback"];
            /** Guidance */
            guidance: string;
            /**
             * Version
             * @default null
             */
            version: number | null;
            /**
             * Saved At
             * @default null
             */
            saved_at: string | null;
            /**
             * Historical
             * @default false
             */
            historical: boolean;
            /**
             * Draft Id
             * @default null
             */
            draft_id: string | null;
            /**
             * Base Version
             * @default null
             */
            base_version: number | null;
            /**
             * Changes
             * @default []
             */
            changes: components["schemas"]["UiItemDiff"][];
            /**
             * Hotel Changed
             * @default false
             */
            hotel_changed: boolean;
            /**
             * Expires At
             * @default null
             */
            expires_at: string | null;
            /**
             * Status
             * @default null
             */
            status: ("staged" | "confirmed") | null;
            /**
             * Expired
             * @default false
             */
            expired: boolean;
            /**
             * Conditions Changed
             * @default false
             */
            conditions_changed: boolean;
            /**
             * Version Changed
             * @default false
             */
            version_changed: boolean;
        };
        /** ValidationCheck */
        UiValidationCheck: {
            /** Subject */
            subject: string;
            /**
             * Status
             * @enum {string}
             */
            status: "verified" | "unknown" | "conflict";
            /** Code */
            code: string;
            /** Message */
            message: string;
        };
        /** ValidationFeedback */
        UiValidationFeedback: {
            /**
             * Status
             * @enum {string}
             */
            status: "complete" | "partial" | "conflict";
            /** Checks */
            checks: components["schemas"]["UiValidationCheck"][];
            /** Known Cost */
            known_cost: string;
            /** Estimated Cost */
            estimated_cost: string;
            /**
             * Scope
             * @default 按当前来源与报价校验；路线时长为估算，临时闭馆与未核实费用仍需出行前确认
             */
            scope: string;
            /** Check Counts */
            check_counts: {
                [key: string]: number;
            };
            /** Truncated */
            truncated: boolean;
        };
        /** @enum {string} */
        UiBusinessKind: "answer_only" | "draft_staged" | "stage_failed" | "confirmed";
        /**
         * BusinessResult
         * @description Small server facts; never derive a business commit from runtime text.
         */
        UiBusinessResult: {
            kind: components["schemas"]["UiBusinessKind"];
            /**
             * Draft Id
             * @default null
             */
            draft_id: string | null;
            /**
             * Plan Id
             * @default null
             */
            plan_id: string | null;
            /**
             * Validation Status
             * @default null
             */
            validation_status: ("complete" | "partial" | "conflict") | null;
            /** @default null */
            code: components["schemas"]["UiErrorCode"] | null;
            /** @default null */
            reason: components["schemas"]["UiStageReason"] | null;
            /**
             * Version
             * @default null
             */
            version: number | null;
        };
        /** @enum {string} */
        UiErrorCode: "validation" | "blocked" | "unavailable" | "timeout" | "rate_limited" | "provider_error" | "conflict" | "cancelled";
        /** @enum {string} */
        UiEventKind: "started" | "text" | "tool_started" | "tool_finished" | "presentation" | "context_compacted" | "completed" | "failed" | "cancelled" | "partial" | "awaiting_user";
        /**
         * RunContext
         * @description 由服务端生成的业务 ID；不能把 SDK session_id 当成用户身份。
         */
        UiRunContext: {
            /**
             * User Id
             * Format: uuid
             */
            user_id: string;
            /**
             * Session Id
             * Format: uuid
             */
            session_id?: string;
            /**
             * Run Id
             * Format: uuid
             */
            run_id?: string;
        };
        /** @enum {string} */
        UiStageReason: "plan_exists" | "patch_invalid" | "repair_limit" | "other";
        /** @enum {string} */
        UiToolReason: "tool_call_cap" | "repair_limit" | "repeat_blocked" | "result_too_long" | "unregistered_tool" | "context_reuse" | "evidence_missing" | "offer_unknown_id" | "not_found" | "live_hold_disabled" | "plan_exists" | "patch_invalid" | "revision_stale" | "lodging_budget_conflict" | "hotel_search_location_required" | "hotel_missing_fields" | "hotel_room_preferences_missing" | "hotel_external_validation" | "hotel_external_unavailable" | "hotel_api_unconfigured" | "schema" | "other" | "conversation_incomplete" | "conversation_state_unavailable" | "max_turns";
        /**
         * RuntimeEvent
         * @description 前端/CLI 所需的最小事件；text 是用户输出，不进入公共 Trace。
         */
        UiRuntimeEvent: {
            context: components["schemas"]["UiRunContext"];
            kind: components["schemas"]["UiEventKind"];
            /**
             * Text
             * @default
             */
            text: string;
            /**
             * Tool Name
             * @default null
             */
            tool_name: string | null;
            /** @default null */
            code: components["schemas"]["UiErrorCode"] | null;
            /** @default null */
            reason: components["schemas"]["UiToolReason"] | null;
            /**
             * Tool Call Id
             * @default null
             */
            tool_call_id: string | null;
            /**
             * Argument Keys
             * @default []
             */
            argument_keys: string[];
            /**
             * Result Empty
             * @default null
             */
            result_empty: boolean | null;
            /**
             * Presentation
             * @default null
             */
            presentation: {
                [key: string]: unknown;
            } | null;
            /**
             * Occurred At
             * Format: date-time
             */
            occurred_at?: string;
            /**
             * Request Revision
             * @default null
             */
            request_revision: number | null;
            /**
             * Evidence Ids
             * @default []
             */
            evidence_ids: string[];
            /** @default null */
            business_result: components["schemas"]["UiBusinessResult"] | null;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    models_models_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ModelOption"][];
                };
            };
        };
    };
    get_preferences_preferences_get: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Preferences"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_preferences_preferences_delete: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PreferenceVersion"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Preferences"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    patch_preferences_preferences_patch: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PreferencePatch"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Preferences"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    health_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
        };
    };
    articles_articles_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Article"][];
                };
            };
        };
    };
    article_articles__article_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                article_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Article"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    demo_login_demo_login_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["DemoLogin"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DemoIdentity"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_sessions_sessions_get: {
        parameters: {
            query?: {
                limit?: number;
                cursor?: string | null;
            };
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SessionPage"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    new_session_sessions_post: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SessionView"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_runs_sessions__session_id__runs_get: {
        parameters: {
            query?: {
                limit?: number;
                before?: string | null;
            };
            header?: {
                authorization?: string | null;
            };
            path: {
                session_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RunPage"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_session_sessions__session_id__get: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path: {
                session_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SessionView"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_travel_request_sessions__session_id__request_get: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path: {
                session_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RequestView"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    patch_travel_request_sessions__session_id__request_patch: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path: {
                session_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RequestPatch"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RequestUpdateView"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    message_sessions__session_id__messages_post: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path: {
                session_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["MessageInput"];
            };
        };
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RunView"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_run_runs__run_id__get: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path: {
                run_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RunView"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    cancel_run_runs__run_id__cancel_post: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path: {
                run_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RunView"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    events_runs__run_id__events_get: {
        parameters: {
            query?: {
                after?: number;
            };
            header?: {
                "last-event-id"?: string | null;
                authorization?: string | null;
            };
            path: {
                run_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_plan_plans__plan_id__get: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path: {
                plan_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PlanView"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_calendar_plans__plan_id__calendar_ics_get: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path: {
                plan_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    hold_hotel_sessions__session_id__hotel_holds_post: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path: {
                session_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["HoldHotelInput"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Booking"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    session_bookings_sessions__session_id__bookings_get: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path: {
                session_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Booking"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_booking_bookings__booking_id__get: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path: {
                booking_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Booking"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    confirm_booking_bookings__booking_id__confirm_post: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path: {
                booking_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Booking"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    reconcile_booking_bookings__booking_id__reconcile_post: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path: {
                booking_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Booking"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_draft_plan_drafts__draft_id__get: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path: {
                draft_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PlanView"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    confirm_plan_plan_drafts__draft_id__confirm_post: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path: {
                draft_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SavedPlan"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    lock_items_plans__plan_id__locks_patch: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path: {
                plan_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LockInput"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SavedPlan"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
