/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/preferences": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Preferences */
        get: operations["get_preferences_preferences_get"];
        put?: never;
        post?: never;
        /** Delete Preferences */
        delete: operations["delete_preferences_preferences_delete"];
        options?: never;
        head?: never;
        /** Patch Preferences */
        patch: operations["patch_preferences_preferences_patch"];
        trace?: never;
    };
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["health_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/articles": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Articles */
        get: operations["articles_articles_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/articles/{article_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Article */
        get: operations["article_articles__article_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/demo/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Demo Login */
        post: operations["demo_login_demo_login_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/sessions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** New Session */
        post: operations["new_session_sessions_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/sessions/{session_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Session */
        get: operations["get_session_sessions__session_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/sessions/{session_id}/request": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Travel Request */
        get: operations["get_travel_request_sessions__session_id__request_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Patch Travel Request */
        patch: operations["patch_travel_request_sessions__session_id__request_patch"];
        trace?: never;
    };
    "/sessions/{session_id}/messages": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Message */
        post: operations["message_sessions__session_id__messages_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/runs/{run_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Run */
        get: operations["get_run_runs__run_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/runs/{run_id}/cancel": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Cancel Run */
        post: operations["cancel_run_runs__run_id__cancel_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/runs/{run_id}/events": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Events */
        get: operations["events_runs__run_id__events_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/plans/{plan_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Plan */
        get: operations["get_plan_plans__plan_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/sessions/{session_id}/hotel-holds": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Hold Hotel */
        post: operations["hold_hotel_sessions__session_id__hotel_holds_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/sessions/{session_id}/bookings": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Session Bookings */
        get: operations["session_bookings_sessions__session_id__bookings_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/bookings/{booking_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Booking */
        get: operations["get_booking_bookings__booking_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/bookings/{booking_id}/confirm": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Confirm Booking */
        post: operations["confirm_booking_bookings__booking_id__confirm_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/bookings/{booking_id}/reconcile": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Reconcile Booking */
        post: operations["reconcile_booking_bookings__booking_id__reconcile_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/plan-drafts/{draft_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Draft */
        get: operations["get_draft_plan_drafts__draft_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/plan-drafts/{draft_id}/confirm": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Confirm Plan */
        post: operations["confirm_plan_plan_drafts__draft_id__confirm_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/plans/{plan_id}/locks": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Lock Items */
        patch: operations["lock_items_plans__plan_id__locks_patch"];
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** Article */
        Article: {
            /** Article Id */
            article_id: string;
            /**
             * City
             * @default 京都
             * @constant
             */
            city: "京都";
            /** Title */
            title: string;
            /** Text */
            text: string;
            /**
             * Category
             * @default guide
             */
            category: string;
            /**
             * Mentioned Places
             * @default []
             */
            mentioned_places: string[];
            source: components["schemas"]["Source"];
        };
        /** Booking */
        Booking: {
            /**
             * Booking Id
             * Format: uuid
             */
            booking_id: string;
            /**
             * Client Ref
             * Format: uuid
             */
            client_ref: string;
            /**
             * Session Id
             * Format: uuid
             */
            session_id: string;
            /**
             * Evidence Id
             * Format: uuid
             */
            evidence_id: string;
            offer: components["schemas"]["HotelOffer"];
            /** Total */
            total: string;
            /** Source Ref */
            source_ref: string;
            /** Content Version */
            content_version: string | null;
            /** @default quoted */
            status: components["schemas"]["BookingStatus"];
            /** Hold Id */
            hold_id: string | null;
            /** Expires At */
            expires_at: string | null;
            /** Order Id */
            order_id: string | null;
            error_code: components["schemas"]["ErrorCode"] | null;
            /**
             * History
             * @default []
             */
            history: components["schemas"]["BookingChange"][];
            /**
             * Data Mode
             * @default fixture
             * @constant
             */
            data_mode: "fixture";
        };
        /** BookingChange */
        BookingChange: {
            status: components["schemas"]["BookingStatus"];
            /**
             * At
             * Format: date-time
             */
            at: string;
            /** Reason */
            reason: string;
        };
        /** @enum {string} */
        BookingStatus: "quoted" | "held" | "confirmed" | "booked" | "failed" | "unknown" | "expired";
        /** DemoIdentity */
        DemoIdentity: {
            /**
             * User Id
             * Format: uuid
             */
            user_id: string;
            /** Token */
            token: string;
            /**
             * Expires At
             * Format: date-time
             */
            expires_at: string;
        };
        /** DemoLogin */
        DemoLogin: {
            /**
             * Display Name
             * @default 旅行者
             */
            display_name: string;
        };
        /** @enum {string} */
        ErrorCode: "validation" | "blocked" | "unavailable" | "timeout" | "rate_limited" | "provider_error" | "conflict" | "cancelled";
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** HoldHotelInput */
        HoldHotelInput: {
            /**
             * Offer Id
             * Format: uuid
             */
            offer_id: string;
            /** Expected Revision */
            expected_revision: number;
        };
        /** HotelCard */
        HotelCard: {
            /**
             * Offer Id
             * Format: uuid
             */
            offer_id: string;
            /** Rate Id */
            rate_id: string;
            /** Hotel Id */
            hotel_id: string;
            /** Hotel Name */
            hotel_name: string;
            /** Room Type */
            room_type: string;
            /** Currency */
            currency: string;
            /** Base Amount */
            base_amount: string;
            /** Tax Amount */
            tax_amount: string | null;
            /** Fee Amount */
            fee_amount: string | null;
            /** Breakfast */
            breakfast: boolean;
            /** Refundable */
            refundable: boolean;
            /**
             * Quoted At
             * Format: date-time
             */
            quoted_at: string;
            /**
             * Expires At
             * Format: date-time
             */
            expires_at: string;
            /** Stay */
            stay: {
                [key: string]: unknown;
            };
            /** Request Revision */
            request_revision: number;
            /** Total */
            total: string | null;
            /** Lodging Exceeds Trip Budget */
            lodging_exceeds_trip_budget: boolean | null;
            /**
             * Data Mode
             * @constant
             */
            data_mode: "fixture";
            /**
             * Evidence Id
             * Format: uuid
             */
            evidence_id: string;
            /** Source Ref */
            source_ref: string | null;
            /** Content Version */
            content_version: string | null;
        };
        /** HotelOffer */
        HotelOffer: {
            /**
             * Offer Id
             * Format: uuid
             */
            offer_id: string;
            /** Rate Id */
            rate_id: string;
            /** Hotel Id */
            hotel_id: string;
            /** Hotel Name */
            hotel_name: string;
            /** Room Type */
            room_type: string;
            /** Currency */
            currency: string;
            /** Base Amount */
            base_amount: string;
            /** Tax Amount */
            tax_amount: string | null;
            /** Fee Amount */
            fee_amount: string | null;
            /** Breakfast */
            breakfast: boolean;
            /** Refundable */
            refundable: boolean;
            /**
             * Quoted At
             * Format: date-time
             */
            quoted_at: string;
            /**
             * Expires At
             * Format: date-time
             */
            expires_at: string;
            request: components["schemas"]["TravelRequest"];
        };
        /** ItemDiff */
        ItemDiff: {
            /**
             * Item Id
             * Format: uuid
             */
            item_id: string;
            /**
             * Op
             * @enum {string}
             */
            op: "add" | "update" | "remove";
            before?: components["schemas"]["PlanItem"] | null;
            after?: components["schemas"]["PlanItem"] | null;
        };
        /** LockInput */
        LockInput: {
            /** Expected Version */
            expected_version: number;
            /** Locked Item Ids */
            locked_item_ids: string[];
        };
        /** MessageInput */
        MessageInput: {
            /**
             * Client Message Id
             * Format: uuid
             */
            client_message_id: string;
            /** Text */
            text: string;
            /**
             * Mode
             * @default offline
             * @enum {string}
             */
            mode: "offline" | "live";
        };
        /** PlanCard */
        PlanCard: {
            /**
             * Place Evidence Id
             * Format: uuid
             */
            place_evidence_id: string;
            /**
             * Start
             * Format: date-time
             * @description 含时区的ISO时间；京都当地时间使用+09:00
             */
            start: string;
            /**
             * End
             * Format: date-time
             * @description 含时区的ISO时间；京都当地时间使用+09:00
             */
            end: string;
            /** Route Evidence Id */
            route_evidence_id: string | null;
            /**
             * Item Id
             * Format: uuid
             */
            item_id: string;
            /**
             * Locked
             * @default false
             */
            locked: boolean;
            /** Name */
            name: string;
            /** Source Ref */
            source_ref: string | null;
            /**
             * Data Mode
             * @enum {string}
             */
            data_mode: "fixture" | "snapshot";
        };
        /** PlanContent */
        PlanContent: {
            /** Items */
            items: components["schemas"]["PlanItem"][];
            /** Hotel Evidence Id */
            hotel_evidence_id?: string | null;
        };
        /** PlanItem */
        PlanItem: {
            /**
             * Place Evidence Id
             * Format: uuid
             */
            place_evidence_id: string;
            /**
             * Start
             * Format: date-time
             * @description 含时区的ISO时间；京都当地时间使用+09:00
             */
            start: string;
            /**
             * End
             * Format: date-time
             * @description 含时区的ISO时间；京都当地时间使用+09:00
             */
            end: string;
            /** Route Evidence Id */
            route_evidence_id?: string | null;
            /**
             * Item Id
             * Format: uuid
             */
            item_id?: string;
            /**
             * Locked
             * @default false
             */
            locked: boolean;
        };
        /** PlanView */
        PlanView: {
            /**
             * Plan Id
             * Format: uuid
             */
            plan_id: string;
            /** Request Revision */
            request_revision: number;
            /** Cards */
            cards: components["schemas"]["PlanCard"][];
            hotel: components["schemas"]["HotelCard"] | null;
            /** Hotel Evidence Id */
            hotel_evidence_id: string | null;
            /** Needs Refresh */
            needs_refresh: string[];
            validation: components["schemas"]["ValidationFeedback"];
            /** Guidance */
            guidance: string;
            /** Version */
            version: number | null;
            /** Saved At */
            saved_at: string | null;
            /**
             * Historical
             * @default false
             */
            historical: boolean;
            /** Draft Id */
            draft_id: string | null;
            /** Base Version */
            base_version: number | null;
            /**
             * Changes
             * @default []
             */
            changes: components["schemas"]["ItemDiff"][];
            /**
             * Hotel Changed
             * @default false
             */
            hotel_changed: boolean;
            /** Expires At */
            expires_at: string | null;
            /** Status */
            status: ("staged" | "confirmed") | null;
            /**
             * Expired
             * @default false
             */
            expired: boolean;
            /**
             * Conditions Changed
             * @default false
             */
            conditions_changed: boolean;
            /**
             * Version Changed
             * @default false
             */
            version_changed: boolean;
        };
        /** PreferencePatch */
        PreferencePatch: {
            /** Expected Revision */
            expected_revision: number;
            set: components["schemas"]["PreferenceValues"];
        };
        /** PreferenceValues */
        PreferenceValues: {
            /**
             * Interests
             * @default []
             */
            interests: string[];
            /**
             * Soft Constraints
             * @default []
             */
            soft_constraints: string[];
            /** Transport */
            transport?: ("walk" | "transit" | "taxi") | null;
        };
        /** PreferenceVersion */
        PreferenceVersion: {
            /** Expected Revision */
            expected_revision: number;
        };
        /** Preferences */
        Preferences: {
            /**
             * Interests
             * @default []
             */
            interests: string[];
            /**
             * Soft Constraints
             * @default []
             */
            soft_constraints: string[];
            /** Transport */
            transport?: ("walk" | "transit" | "taxi") | null;
            /**
             * Revision
             * @default 0
             */
            revision: number;
        };
        /** RequestPatch */
        RequestPatch: {
            /** Expected Revision */
            expected_revision: number;
            set?: components["schemas"]["TravelConditions"];
            /**
             * Clear
             * @default []
             */
            clear: string[];
        };
        /** RequestUpdate */
        RequestUpdate: {
            request: components["schemas"]["TravelRequest"];
            /** Changed Fields */
            changed_fields: string[];
        };
        /** RunView */
        RunView: {
            /**
             * Run Id
             * Format: uuid
             */
            run_id: string;
            /**
             * Session Id
             * Format: uuid
             */
            session_id: string;
            /** Status */
            status: string;
            /** Mode */
            mode: string;
            /** Answer */
            answer: string;
            /** Error Code */
            error_code: string | null;
            /** Last Sequence */
            last_sequence: number;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Presentations
             * @default []
             */
            presentations: {
                [key: string]: unknown;
            }[];
        };
        /** SavedPlan */
        SavedPlan: {
            /**
             * Plan Id
             * Format: uuid
             */
            plan_id: string;
            /** Version */
            version: number;
            /** Request Revision */
            request_revision: number;
            content: components["schemas"]["PlanContent"];
            validation: components["schemas"]["ValidationReport"];
            /**
             * Saved At
             * Format: date-time
             */
            saved_at: string;
        };
        /** SessionView */
        SessionView: {
            /**
             * Session Id
             * Format: uuid
             */
            session_id: string;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
        };
        /** Source */
        Source: {
            /**
             * Provider
             * @enum {string}
             */
            provider: "osm" | "wikivoyage";
            /** Source Ref */
            source_ref: string;
            /** Content Version */
            content_version: string;
            /**
             * Retrieved At
             * Format: date-time
             */
            retrieved_at: string;
            /** License */
            license: string;
            /** License Url */
            license_url: string;
            /** Attribution */
            attribution: string;
            /**
             * Data Mode
             * @default snapshot
             * @constant
             */
            data_mode: "snapshot";
        };
        /** TravelConditions */
        TravelConditions: {
            /** City */
            city?: "京都" | null;
            /** Start Date */
            start_date?: string | null;
            /** End Date */
            end_date?: string | null;
            /**
             * Timezone
             * @default Asia/Tokyo
             * @constant
             */
            timezone: "Asia/Tokyo";
            /** Adults */
            adults?: number | null;
            /** Child Ages */
            child_ages?: number[] | null;
            /** Rooms */
            rooms?: number | null;
            /** Budget */
            budget?: number | string | null;
            /**
             * Currency
             * @default JPY
             * @constant
             */
            currency: "JPY";
            /** Transport */
            transport?: ("walk" | "transit" | "taxi") | null;
            /** Departure Time */
            departure_time?: string | null;
            /**
             * Interests
             * @default []
             */
            interests: string[];
            /**
             * Hard Constraints
             * @default []
             */
            hard_constraints: string[];
            /**
             * Soft Constraints
             * @default []
             */
            soft_constraints: string[];
        };
        /** TravelRequest */
        TravelRequest: {
            /** City */
            city?: "京都" | null;
            /** Start Date */
            start_date?: string | null;
            /** End Date */
            end_date?: string | null;
            /**
             * Timezone
             * @default Asia/Tokyo
             * @constant
             */
            timezone: "Asia/Tokyo";
            /** Adults */
            adults?: number | null;
            /** Child Ages */
            child_ages?: number[] | null;
            /** Rooms */
            rooms?: number | null;
            /** Budget */
            budget?: string | null;
            /**
             * Currency
             * @default JPY
             * @constant
             */
            currency: "JPY";
            /** Transport */
            transport?: ("walk" | "transit" | "taxi") | null;
            /** Departure Time */
            departure_time?: string | null;
            /**
             * Interests
             * @default []
             */
            interests: string[];
            /**
             * Hard Constraints
             * @default []
             */
            hard_constraints: string[];
            /**
             * Soft Constraints
             * @default []
             */
            soft_constraints: string[];
            /**
             * Revision
             * @default 0
             */
            revision: number;
        };
        /** ValidationCheck */
        ValidationCheck: {
            /** Subject */
            subject: string;
            /**
             * Status
             * @enum {string}
             */
            status: "verified" | "unknown" | "conflict";
            /** Code */
            code: string;
            /** Message */
            message: string;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
        /** ValidationFeedback */
        ValidationFeedback: {
            /**
             * Status
             * @enum {string}
             */
            status: "complete" | "partial" | "conflict";
            /** Checks */
            checks: components["schemas"]["ValidationCheck"][];
            /** Known Cost */
            known_cost: string;
            /** Estimated Cost */
            estimated_cost: string;
            /**
             * Scope
             * @default 按当前快照和模拟报价校验；路线为估算，未覆盖实时天气、临时闭馆和未知费用
             */
            scope: string;
            /** Check Counts */
            check_counts: {
                [key: string]: number;
            };
            /** Truncated */
            truncated: boolean;
        };
        /** ValidationReport */
        ValidationReport: {
            /**
             * Status
             * @enum {string}
             */
            status: "complete" | "partial" | "conflict";
            /** Checks */
            checks: components["schemas"]["ValidationCheck"][];
            /** Known Cost */
            known_cost: string;
            /** Estimated Cost */
            estimated_cost: string;
            /**
             * Scope
             * @default 按当前快照和模拟报价校验；路线为估算，未覆盖实时天气、临时闭馆和未知费用
             */
            scope: string;
        };
        /** Comparison */
        UiComparison: {
            /** Comparable */
            comparable: boolean;
            /** Reasons */
            reasons: string[];
            /** Lowest Offer Ids */
            lowest_offer_ids: string[];
            /** Scope */
            scope: string;
        };
        /** HotelCard */
        UiHotelCard: {
            /**
             * Offer Id
             * Format: uuid
             */
            offer_id: string;
            /** Rate Id */
            rate_id: string;
            /** Hotel Id */
            hotel_id: string;
            /** Hotel Name */
            hotel_name: string;
            /** Room Type */
            room_type: string;
            /** Currency */
            currency: string;
            /** Base Amount */
            base_amount: string;
            /** Tax Amount */
            tax_amount: string | null;
            /** Fee Amount */
            fee_amount: string | null;
            /** Breakfast */
            breakfast: boolean;
            /** Refundable */
            refundable: boolean;
            /**
             * Quoted At
             * Format: date-time
             */
            quoted_at: string;
            /**
             * Expires At
             * Format: date-time
             */
            expires_at: string;
            /** Stay */
            stay: {
                [key: string]: unknown;
            };
            /** Request Revision */
            request_revision: number;
            /** Total */
            total: string | null;
            /** Lodging Exceeds Trip Budget */
            lodging_exceeds_trip_budget: boolean | null;
            /**
             * Data Mode
             * @constant
             */
            data_mode: "fixture";
            /**
             * Evidence Id
             * Format: uuid
             */
            evidence_id: string;
            /** Source Ref */
            source_ref: string | null;
            /** Content Version */
            content_version: string | null;
        };
        /** HotelPresentation */
        UiHotelPresentation: {
            /**
             * Component
             * @constant
             */
            component: "hotel_comparison";
            /** Cards */
            cards: components["schemas"]["UiHotelCard"][];
            comparison: components["schemas"]["UiComparison"];
        };
        /** ItemDiff */
        UiItemDiff: {
            /**
             * Item Id
             * Format: uuid
             */
            item_id: string;
            /**
             * Op
             * @enum {string}
             */
            op: "add" | "update" | "remove";
            /** @default null */
            before: components["schemas"]["UiPlanItem"] | null;
            /** @default null */
            after: components["schemas"]["UiPlanItem"] | null;
        };
        /** PlanCard */
        UiPlanCard: {
            /**
             * Place Evidence Id
             * Format: uuid
             */
            place_evidence_id: string;
            /**
             * Start
             * Format: date-time
             * @description 含时区的ISO时间；京都当地时间使用+09:00
             */
            start: string;
            /**
             * End
             * Format: date-time
             * @description 含时区的ISO时间；京都当地时间使用+09:00
             */
            end: string;
            /**
             * Route Evidence Id
             * @default null
             */
            route_evidence_id: string | null;
            /**
             * Item Id
             * Format: uuid
             */
            item_id: string;
            /**
             * Locked
             * @default false
             */
            locked: boolean;
            /** Name */
            name: string;
            /** Source Ref */
            source_ref: string | null;
            /**
             * Data Mode
             * @enum {string}
             */
            data_mode: "fixture" | "snapshot";
        };
        /** PlanItem */
        UiPlanItem: {
            /**
             * Place Evidence Id
             * Format: uuid
             */
            place_evidence_id: string;
            /**
             * Start
             * Format: date-time
             * @description 含时区的ISO时间；京都当地时间使用+09:00
             */
            start: string;
            /**
             * End
             * Format: date-time
             * @description 含时区的ISO时间；京都当地时间使用+09:00
             */
            end: string;
            /**
             * Route Evidence Id
             * @default null
             */
            route_evidence_id: string | null;
            /**
             * Item Id
             * Format: uuid
             */
            item_id?: string;
            /**
             * Locked
             * @default false
             */
            locked: boolean;
        };
        /** PlanView */
        UiPlanView: {
            /**
             * Plan Id
             * Format: uuid
             */
            plan_id: string;
            /** Request Revision */
            request_revision: number;
            /** Cards */
            cards: components["schemas"]["UiPlanCard"][];
            hotel: components["schemas"]["UiHotelCard"] | null;
            /** Hotel Evidence Id */
            hotel_evidence_id: string | null;
            /** Needs Refresh */
            needs_refresh: string[];
            validation: components["schemas"]["UiValidationFeedback"];
            /** Guidance */
            guidance: string;
            /**
             * Version
             * @default null
             */
            version: number | null;
            /**
             * Saved At
             * @default null
             */
            saved_at: string | null;
            /**
             * Historical
             * @default false
             */
            historical: boolean;
            /**
             * Draft Id
             * @default null
             */
            draft_id: string | null;
            /**
             * Base Version
             * @default null
             */
            base_version: number | null;
            /**
             * Changes
             * @default []
             */
            changes: components["schemas"]["UiItemDiff"][];
            /**
             * Hotel Changed
             * @default false
             */
            hotel_changed: boolean;
            /**
             * Expires At
             * @default null
             */
            expires_at: string | null;
            /**
             * Status
             * @default null
             */
            status: ("staged" | "confirmed") | null;
            /**
             * Expired
             * @default false
             */
            expired: boolean;
            /**
             * Conditions Changed
             * @default false
             */
            conditions_changed: boolean;
            /**
             * Version Changed
             * @default false
             */
            version_changed: boolean;
        };
        /** ValidationCheck */
        UiValidationCheck: {
            /** Subject */
            subject: string;
            /**
             * Status
             * @enum {string}
             */
            status: "verified" | "unknown" | "conflict";
            /** Code */
            code: string;
            /** Message */
            message: string;
        };
        /** ValidationFeedback */
        UiValidationFeedback: {
            /**
             * Status
             * @enum {string}
             */
            status: "complete" | "partial" | "conflict";
            /** Checks */
            checks: components["schemas"]["UiValidationCheck"][];
            /** Known Cost */
            known_cost: string;
            /** Estimated Cost */
            estimated_cost: string;
            /**
             * Scope
             * @default 按当前快照和模拟报价校验；路线为估算，未覆盖实时天气、临时闭馆和未知费用
             */
            scope: string;
            /** Check Counts */
            check_counts: {
                [key: string]: number;
            };
            /** Truncated */
            truncated: boolean;
        };
        /** @enum {string} */
        UiErrorCode: "validation" | "blocked" | "unavailable" | "timeout" | "rate_limited" | "provider_error" | "conflict" | "cancelled";
        /** @enum {string} */
        UiEventKind: "started" | "text" | "tool_started" | "tool_finished" | "presentation" | "context_compacted" | "completed" | "failed" | "cancelled" | "partial" | "awaiting_user";
        /**
         * RunContext
         * @description 由服务端生成的业务 ID；不能把 SDK session_id 当成用户身份。
         */
        UiRunContext: {
            /**
             * User Id
             * Format: uuid
             */
            user_id: string;
            /**
             * Session Id
             * Format: uuid
             */
            session_id?: string;
            /**
             * Run Id
             * Format: uuid
             */
            run_id?: string;
        };
        /**
         * RuntimeEvent
         * @description 前端/CLI 所需的最小事件；text 是用户输出，不进入公共 Trace。
         */
        UiRuntimeEvent: {
            context: components["schemas"]["UiRunContext"];
            kind: components["schemas"]["UiEventKind"];
            /**
             * Text
             * @default
             */
            text: string;
            /**
             * Tool Name
             * @default null
             */
            tool_name: string | null;
            /** @default null */
            code: components["schemas"]["UiErrorCode"] | null;
            /**
             * Tool Call Id
             * @default null
             */
            tool_call_id: string | null;
            /**
             * Argument Keys
             * @default []
             */
            argument_keys: string[];
            /**
             * Result Empty
             * @default null
             */
            result_empty: boolean | null;
            /**
             * Presentation
             * @default null
             */
            presentation: {
                [key: string]: unknown;
            } | null;
            /**
             * Occurred At
             * Format: date-time
             */
            occurred_at?: string;
            /**
             * Request Revision
             * @default null
             */
            request_revision: number | null;
            /**
             * Evidence Ids
             * @default []
             */
            evidence_ids: string[];
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    get_preferences_preferences_get: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Preferences"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_preferences_preferences_delete: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PreferenceVersion"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Preferences"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    patch_preferences_preferences_patch: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PreferencePatch"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Preferences"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    health_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
        };
    };
    articles_articles_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Article"][];
                };
            };
        };
    };
    article_articles__article_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                article_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Article"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    demo_login_demo_login_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["DemoLogin"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DemoIdentity"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    new_session_sessions_post: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SessionView"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_session_sessions__session_id__get: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path: {
                session_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SessionView"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_travel_request_sessions__session_id__request_get: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path: {
                session_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TravelRequest"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    patch_travel_request_sessions__session_id__request_patch: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path: {
                session_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RequestPatch"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RequestUpdate"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    message_sessions__session_id__messages_post: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path: {
                session_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["MessageInput"];
            };
        };
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RunView"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_run_runs__run_id__get: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path: {
                run_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RunView"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    cancel_run_runs__run_id__cancel_post: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path: {
                run_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RunView"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    events_runs__run_id__events_get: {
        parameters: {
            query?: {
                after?: number;
            };
            header?: {
                "last-event-id"?: string | null;
                authorization?: string | null;
            };
            path: {
                run_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_plan_plans__plan_id__get: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path: {
                plan_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PlanView"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    hold_hotel_sessions__session_id__hotel_holds_post: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path: {
                session_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["HoldHotelInput"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Booking"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    session_bookings_sessions__session_id__bookings_get: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path: {
                session_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Booking"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_booking_bookings__booking_id__get: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path: {
                booking_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Booking"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    confirm_booking_bookings__booking_id__confirm_post: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path: {
                booking_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Booking"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    reconcile_booking_bookings__booking_id__reconcile_post: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path: {
                booking_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Booking"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_draft_plan_drafts__draft_id__get: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path: {
                draft_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PlanView"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    confirm_plan_plan_drafts__draft_id__confirm_post: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path: {
                draft_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SavedPlan"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    lock_items_plans__plan_id__locks_patch: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path: {
                plan_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LockInput"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SavedPlan"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
